# Generated by Django 4.1.7 on 2023-06-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_alter_address_pincode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_country',
            field=models.ManyToManyField(null=True, related_name='books', to='book_outlet.country'),
        ),
    ]
